before_script:
  - apk add --no-cache py-pip

variables:
  CONTAINER_IMAGE: sickrage/sickrage:$(cat sickrage/version.txt)
  CONTAINER_IMAGE_LATEST: sickrage/sickrage:latest

  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://localhost:2375

services:
  - docker:dind

build:
  stage: build
  image: docker:latest
  script:
    - echo -n $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker build --network host -t $CONTAINER_IMAGE_LATEST .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_LATEST}
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_LATEST}
  only:
    - master
  except:
    - tags