image: docker:latest

services:
  - name: docker:dind

before_script:
  - apk add --no-cache py-pip
  - pip install docker-compose
  - echo -n $CI_REGISTRY_PASSWORD | docker login -u "$CI_REGISTRY_USER" --password-stdin

build-master:
  stage: build
  script:
    - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VERSION=`cat sickrage/version.txt` -t sickrage/sickrage:latest .
    - docker push "sickrage/sickrage:latest"
  only:
    - master
  except:
    - tags

build-dev:
  stage: build
  script:
    - docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` --build-arg VERSION=`cat sickrage/version.txt` -t sickrage/sickrage:$CI_COMMIT_REF_SLUG .
    - docker push sickrage/sickrage:$CI_COMMIT_REF_SLUG
  except:
    - master
    - tags