language: python
python:
  - 2.7.10

sudo: false

branches:
  only:
    - master

install: .travis/install.sh

cache: pip

before_script:
 - chmod +x ./tests/*.py

script:
  - python -m unittest discover tests

after_failure:
  - cat ./tests/Logs/sickrage.log

notifications:
  irc:
    channels:
      - "irc.freenode.net#sickrage"
    use_notice: true
    skip_join: true

  email:
    on_success: change
    on_failure: change
