project_identifier: sickragetv
api_key_env: CROWDIN_API_KEY
base_url: https://api.crowdin.com
base_path: .
files:
  -
    source: /sickrage/locale/messages.pot
    translation: /sickrage/locale/%locale_with_underscore%/LC_MESSAGES/messages.po
