version: '2'

services:
  sickrage:
    container_name: sickrage
    build: .
    ports:
      - 8081:8081
    volumes:
      - D:\docker\sickrage\config:/root/.sickrage
      - D:\Downloads:/downloads
      - D:\Videos\TV:/tv
    environment:
      - TZ=Canada/Pacific
#      - LANG=en_US.UTF-8
#      - LANGUAGE=en_US:en
#      - LC_ALL=en_US.UTF-8