version: '2'

services:
  sickrage:
    container_name: sickrage
    build: .
    ports:
      - 8081:8081
    volumes:
      - /path/to/sickrage/data:/root/.sickrage
      - /path/to/downloads:/downloads
      - /path/to/tv:/tv
      - /path/to/anime:/anime
    environment:
      - TZ=Canada/Pacific
#      - LANG=en_US.UTF-8
#      - LANGUAGE=en_US:en
#      - LC_ALL=en_US.UTF-8